# E:\BPCL office\Project2\sync_photos.ps1
# Script to synchronize site folders and generate photos_data.js

$indexHtmlPath = "E:\BPCL office\Project2\index.html"
$sitesDetailsPath = "G:\My Drive\TL-PATIL- 2026\IFMS\Sites Details"
$outputJsPath = "E:\BPCL office\Project2\photos_data.js"

# Create target directories if they don't exist
if (!(Test-Path -Path $sitesDetailsPath)) {
    Write-Host "Creating Sites Details base directory: $sitesDetailsPath" -ForegroundColor Yellow
    New-Item -Path $sitesDetailsPath -ItemType Directory -Force | Out-Null
}

Write-Host "Reading index.html to fetch dealer list..." -ForegroundColor Cyan
if (!(Test-Path -Path $indexHtmlPath)) {
    Write-Error "index.html not found at $indexHtmlPath!"
    exit
}

$content = Get-Content -Path $indexHtmlPath -Raw

# Extract dealersData block
$startIndex = $content.IndexOf("const dealersData = [")
if ($startIndex -eq -1) {
    Write-Error "Could not find dealersData block in index.html!"
    exit
}

$endIndex = $content.IndexOf("];", $startIndex)
$dealersBlock = $content.Substring($startIndex, $endIndex - $startIndex)

# Match each dealer object
$dealerPattern = "(?s)\{[^{}]+\}"
$dealerMatches = [regex]::Matches($dealersBlock, $dealerPattern)

Write-Host "Found $($dealerMatches.Count) dealers. Scanning folders..." -ForegroundColor Cyan

$photosMap = @{}
$newFoldersCount = 0

foreach ($match in $dealerMatches) {
    $dealerText = $match.Value
    
    # Extract CC Number
    $ccMatch = [regex]::Match($dealerText, "ccNumber:\s*'([^']+)'")
    if (!$ccMatch.Success) { continue }
    $ccNumber = $ccMatch.Groups[1].Value
    
    # Extract Outlet Name
    $nameMatch = [regex]::Match($dealerText, "outletName:\s*'([^']+)'")
    if (!$nameMatch.Success) { continue }
    $outletName = $nameMatch.Groups[1].Value
    
    # Check if folder exists starting with CC Number
    $folder = Get-ChildItem -Path $sitesDetailsPath -Directory -Filter "$ccNumber*" | Select-Object -First 1
    
    $folderName = ""
    if ($folder) {
        $folderName = $folder.Name
    } else {
        # Create new folder
        $sanitizedName = $outletName -replace '[^A-Za-z0-9 ]', ''
        $sanitizedName = $sanitizedName.Trim() -replace '\s+', '_'
        $sanitizedName = $sanitizedName.ToUpper()
        $folderName = "${ccNumber}_${sanitizedName}"
        
        $newFolderPath = Join-Path -Path $sitesDetailsPath -ChildPath $folderName
        Write-Host "Creating missing folder: $folderName" -ForegroundColor Green
        New-Item -Path $newFolderPath -ItemType Directory -Force | Out-Null
        $newFoldersCount++
    }
    
    # Scan for photos in this folder
    $fullFolderPath = Join-Path -Path $sitesDetailsPath -ChildPath $folderName
    $photoFiles = Get-ChildItem -Path $fullFolderPath -File | Where-Object { $_.Extension -match '^\.(jpg|jpeg|png|webp|gif)$' }
    
    $photosList = @()
    foreach ($file in $photoFiles) {
        $photosList += $file.Name
    }
    
    # Convert path slashes to forward slashes for web compatibility
    $webFolderPath = $fullFolderPath.Replace("\", "/")
    
    $photosMap[$ccNumber] = @{
        folderName = $folderName
        folderPath = $webFolderPath
        photos = $photosList
    }
}

# Convert map to JSON
$json = $photosMap | ConvertTo-Json -Depth 5

# Format as JavaScript file content
$jsContent = @"
// Automatically generated by sync_photos.ps1
// Contains the photo metadata for each retail outlet matching folders in G:/My Drive/TL-PATIL- 2026/IFMS/Sites Details/

const photosData = $json;
"@

# Write to file
Set-Content -Path $outputJsPath -Value $jsContent -Encoding utf8
Write-Host "Sync complete! Saved to $outputJsPath" -ForegroundColor Cyan
Write-Host "Created $newFoldersCount new folders." -ForegroundColor Cyan
